#DataBase DataSources
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/factory?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  jpa:
    database: mysql
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB